# Generated by Django 4.1.1 on 2022-10-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField(default=0)),
                ('meele_armor', models.IntegerField(default=0)),
                ('pierce_armor', models.IntegerField(default=0)),
                ('range', models.IntegerField(default=0)),
                ('speed', models.FloatField(default=0.1)),
                ('los', models.IntegerField(default=2)),
                ('search_radius', models.IntegerField(default=2)),
                ('creation_time', models.IntegerField(default=25)),
            ],
        ),
    ]
