# Generated by Django 4.1.1 on 2022-10-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agestats', '0002_unit_cost_food_unit_cost_gold_unit_cost_stone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='attack_type',
            field=models.CharField(default='meele', max_length=20),
        ),
    ]
